rejects = {'@objectwin.com': True, '@saibber108.com': True,
           '@smarttechlink.com': True, '@itpeoplecorp.com': True,
           '@ekodus.com': True, '@iconma.com': True, '@ceiamerica.com': True,
           '@gttit.com': True, '@pingthings.io': True,
           '@zoniacmailseven.us': True, '@deegit.com': True,
           '@sightspectrum.com': True, 'sparkpost.com': True,
           '@diverselynx.com': True, '@consmtp.com': True, '@sgainc.com': True,
           '@lat36.com': True, '@spotifypig.firebaseapp.com': True,
           '@kanorsystems.com': True, '@conrep-smtp.com': True,
           '@nityo.com': True, '@colcon.com': True, '@apolisrises.com': True,
           '@compunnel.com': True, '@disys.com': True,
           '@intelliswift.com': True, '@ustechsolutionsinc.com': True,
           '@bayonesolutions.com': True, '@sans.com': True,
           '@compugain.com': True, '@xoriant.com': True,
           '@diligencesys.com': True, '@vbeyond.com': True,
           '@mail.cybercoders.com': True, '@primussoft.com': True,
           '@pyramidci.com': True, '@cyspacetech.com': True,
           'hubspotemail.net': True, '@turnberrysolutions.com': True,
           '@servstaffing.com': True, '@bj-kingservices.com': True,
           '@saranshtech.com': True, '@intonenetworks.com': True,
           '@cardinaltsinc.com': True, '@idctechnologies.com': True,
           '@nvish.com': True, '@savantis.com': True, '@talentburst.com': True,
           '@cardinaltsinc.net': True, '@insightglobal.com': True,
           '@peritosystems.com': True, '@insoursysinc.com': True,
           '@techdigitalcorp.com': True, '@techproviders.com': True,
           '@modis.com': True, '@asciigroup.com': True, '@vitsus.com': True,
           '@4vovn0jqd0ksgbio.9sxq1.5-7uiceaq.na89.bnc.salesforce.com': True,
           '@jconnectinc.com': True, '@sgiccloudtech.com': True,
           '@tekfortune.com': True, '@hightechcommerce.com': True,
           '@judge.com': True, '@aitacs.com': True, '@adcc.com': True,
           '@vsoftconsulting.com': True, '@email.nexxt.com': True,
           '@delivery.email.nexxt.com': True, '@email.nexxt.com': True,
           '@jobspringpartners.com': True, '@mondo.com': True,
           'consulting.com': True, '.net': True, '@cyberthink.com': True,
           'delivery.email': True, '-it.com': True, 'postmaster': True,
           'e-notify': True, 'outlook.in': True}
